DROP VIEW IF EXISTS v_StdSiteJobs;
DROP VIEW IF EXISTS v_StdSiteInfo;
DROP TABLE IF EXISTS StdSiteJobs;
DROP TABLE IF EXISTS StdSiteInfo;
DROP TABLE IF EXISTS StdSiteList;
DROP TABLE IF EXISTS Jobs;
DROP TABLE IF EXISTS GeosPaths;
DROP TABLE IF EXISTS GeosFiles;