[execution]
max_numpy_threads = 2
hours_to_keep = 168
ftp_download_server = 'ftp://example/'
ftp_download_root = '.'
output_path = '.'
std_sites_tar_output = '.'
std_sites_output_base = '.'
job_max_days = 30
start_jobs_freq = 5.0
simulation = true
input_file_pattern = "input_file_*.txt"
status_request_file_pattern = "ginput_status.txt"
success_input_file_dir = "."
failure_input_file_dir = "."
submitted_job_queue = "submitted"
std_site_job_queue = "standard"
error_handler = { type = "Logging" }

[execution.queues.standard]
max_num_procs = 4

[execution.queues.submitted]
max_num_procs = 4

[processing_configuration.std-geosfpit]
required_mets = ["geosfpit-surf-met", "geosfpit-eta-met", "geosfpit-eta-chm"]
ginput = "v1.0.6"
start_date = "2000-01-01"
end_date = "2023-06-01"
generate_automatically = true
ginput_met_key = "fpit-eta"
ginput_output_subdir = "fpit"

[processing_configuration.altco-geosfpit]
required_mets = ["geosfpit-surf-met", "geosfpit-eta-met", "geosit-eta-chm"]
ginput = "v1.2.0"
start_date = "2000-01-01"
end_date = "2023-06-01"
generate_automatically = true
ginput_met_key = "it-eta"
ginput_output_subdir = "it"

[processing_configuration.std-geosit]
required_mets = ["geosit-surf-met", "geosit-eta-met", "geosit-eta-chm"]
ginput = "v1.2.0"
start_date = "2023-06-01"
generate_automatically = true
ginput_met_key = "it-eta"
ginput_output_subdir = "it"

[processing_configuration.std-geosfp]
required_mets = ["geosfp-surf-met", "geosfp-eta-met", "geosfp-eta-chm"]
ginput = "v1.2.0"
start_date = "2000-01-01"
generate_automatically = false                                          # left as false because FP is only for download testing
download_met_automatically = false
ginput_met_key = "fpit-eta"
ginput_output_subdir = "fpit"

[execution.ginput."v1.0.6"]
entry_point_path = "./cli/tests/common/config_target_dummy"
type = "Script"

[execution.ginput."v1.2.0"]
entry_point_path = "./cli/tests/common/config_target_dummy"
type = "Script"

[[blacklist]]
identifier = { type = "SubmitterEmail", submitter = "dummy@oops.com" }
silent = false

[[blacklist]]
identifier = { type = "SubmitterEmail", submitter = "spammer@spammy.com" }
silent = true

[[blacklist]]
identifier = { type = "SubmitterEmail", submitter = "rtfm@rtfm.edu" }
silent = false
reason = "don't request a grid of priors"

[requests.allowed_mets.co_reprocessing]
met_key = 'geosit'
ginput_key = 'v1.2.0'
start_date = "2018-01-01"
end_date = "2018-01-08"

[data]
zgrid_file = './cli/tests/common/config_target_dummy'
base_vmr_file = './cli/tests/common/config_target_dummy'
o2_file_source_url = "https://tccondata.org/2b-private-qc/o2_mean_dmf.dat"
o2_file_path = "o2_mean_dmf.dat"

[data.met_download.geosfpit-eta-met]
url_pattern = "http://goldsfs1.gesdisc.eosdis.nasa.gov/data/GEOS5/DFPITI3NVASM.5.12.4/%Y/%j/.hidden/GEOS.fpit.asm.inst3_3d_asm_Nv.GEOS5124.%Y%m%d_%H%M.V01.nc4"
file_freq_min = 180
earliest_date = "2000-01-01"
download_dir = './cli/tests/common/config_met_dl_dummy/Nv'
days_latency = 1
ginput_met_type = 'met-eta'

[data.met_download.geosfpit-surf-met]
url_pattern = "http://goldsfs1.gesdisc.eosdis.nasa.gov/data/GEOS5/DFPITI3NXASM.5.12.4/%Y/%j/.hidden/GEOS.fpit.asm.inst3_2d_asm_Nx.GEOS5124.%Y%m%d_%H%M.V01.nc4"
file_freq_min = 180
earliest_date = "2000-01-01"
download_dir = './cli/tests/common/config_met_dl_dummy/Nx'
days_latency = 1
ginput_met_type = 'met-2d'

[data.met_download.geosfpit-eta-chm]
url_pattern = "http://goldsfs1.gesdisc.eosdis.nasa.gov/data/GEOS5/DFPITI3NVCHM.5.12.4/%Y/%j/.hidden/GEOS.fpit.asm.inst3_3d_chm_Nv.GEOS5124.%Y%m%d_%H%M.V01.nc4"
file_freq_min = 180
earliest_date = "2000-01-01"
download_dir = './cli/tests/common/config_met_dl_dummy/Nv'
days_latency = 1
ginput_met_type = 'chem-eta'


[data.met_download.geosit-eta-met]
url_pattern = "http://goldsfs1.gesdisc.eosdis.nasa.gov/data/GEOSIT/GEOSIT_ASM_I3_L_V72.5.29.4/%Y/%j/.hidden/GEOS.it.asm.asm_inst_3hr_glo_L576x361_v72.GEOS5294.%Y-%m-%dT%H%M.V01.nc4"
file_freq_min = 180
earliest_date = "2000-01-01"
download_dir = './cli/tests/common/config_met_dl_dummy/Nv'
days_latency = 1
ginput_met_type = 'met-eta'

[data.met_download.geosit-surf-met]
url_pattern = "http://goldsfs1.gesdisc.eosdis.nasa.gov/data/GEOSIT/GEOSIT_ASM_I1_L_SLV.5.29.4/%T/%j/.hidden/GEOS.it.asm.asm_inst_1hr_glo_L576x361_slv.GEOS5294.%Y-%m-%dT%H%M.V01.nc4"
file_freq_min = 180
earliest_date = "2000-01-01"
download_dir = './cli/tests/common/config_met_dl_dummy/Nx'
days_latency = 1
ginput_met_type = 'met-2d'

[data.met_download.geosit-eta-chm]
url_pattern = "http://goldsfs1.gesdisc.eosdis.nasa.gov/data/GEOSIT/GEOSIT_CHM_I3_L_V72.5.29.4/%Y/%j/.hidden/GEOS.it.asm.chm_inst_3hr_glo_L576x361_v72.GEOS5294.%Y-%m-%dT%H%M.V01.nc4"
file_freq_min = 180
earliest_date = "2000-01-01"
download_dir = './cli/tests/common/config_met_dl_dummy/Nv'
days_latency = 1
ginput_met_type = 'chem-eta'


[data.met_download.geosfp-eta-met]
url_pattern = "https://portal.nccs.nasa.gov/datashare/gmao_ops/pub/fp/das/Y%Y/M%m/D%d/GEOS.fp.asm.inst3_3d_asm_Nv.%Y%m%d_%H%M.V01.nc4"
file_freq_min = 180
earliest_date = "2000-01-01"
download_dir = './cli/tests/common/config_met_dl_dummy/Nv'
days_latency = 1
ginput_met_type = 'met-eta'

[data.met_download.geosfp-surf-met]
url_pattern = "https://portal.nccs.nasa.gov/datashare/gmao_ops/pub/fp/das/Y%Y/M%m/D%d/GEOS.fp.asm.inst3_2d_asm_Nx.%Y%m%d_%H%M.V01.nc4"
file_freq_min = 180
earliest_date = "2000-01-01"
download_dir = './cli/tests/common/config_met_dl_dummy/Nx'
days_latency = 1
ginput_met_type = 'met-2d'

[data.met_download.geosfp-eta-chm]
url_pattern = "https://portal.nccs.nasa.gov/datashare/gmao_ops/pub/fp/das/Y%Y/M%m/D%d/GEOS.fp.asm.inst3_3d_chm_Nv.%Y%m%d_%H%M.V01.nc4"
file_freq_min = 180
earliest_date = "2000-01-01"
download_dir = './cli/tests/common/config_met_dl_dummy/Nv'
days_latency = 1
ginput_met_type = 'chem-eta'


[[default_options]]
end_date = "2023-06-01"
processing_configuration = "std-geosfpit"

[[default_options]]
start_date = "2023-06-01"
processing_configuration = "std-geosit"


[email]
from_address = "jobs@test.net"
admin_emails = ["admin@test.net"]
backend = { type = "Testing" }
extra_submitters = []

[timing]
disable_met_download = false
met_download_hours = 6
disable_job = false
job_start_seconds = 60
status_report_seconds = 15
lut_regen_days = 1
input_files_update_days = 1
delete_expired_jobs_hours = 24
disable_std_site_gen = false
std_site_gen_hours = 12
std_site_tar_minutes = 30
disable_reports = true
std_site_json_hours = 1

[auth]
hmac_secret_file = ""
